---
- name: 'Get version'
  shell: "apt-cache madison chrony | awk '{print $3}'"
  check_mode: no
  changed_when: false
  register: register_version

- debug:
    var: register_version.stdout

- name: 'Configure Chrony'
  become: yes
  template:
    src: 'chrony.conf.j2'
    dest: "{{ chrony_conf_file }}"
  notify: 'restart chrony'
